In [ ]:
class person:
    def __init__(self,name, age):
        self.name = name
        self.age = age
Person = person("Bharath",10000)




10000

In [ ]:
Person.name

'Bharath'

In [ ]:
Person.age

10000

In [ ]:
class Car:
    wheels = 4
    def __init__(self, make, year):
        self.make = make
        self.year = year

    def start_engine(self):
        print("Engine started!")

    @classmethod
    def get_wheels(cls):
        return cls.wheels

    @staticmethod
    def is_motor_vehicle():
        return True

In [ ]:
car = Car("Toyota", 2022)

In [ ]:
print(car.make)
print(car.year)

Toyota
2022


In [ ]:
car.start_engine()

Engine started!


In [ ]:
car.get_wheels()

4

In [ ]:
car.is_motor_vehicle()

True

In [ ]:
class person:
  def __init__(self,name,age):
    self._name = name
    self._age = age
  def get_name(self):
    return self._name
  def get_age(self):
    return self._age

In [ ]:
Person = person("kishan",21)

In [ ]:
Person.get_name()

'kishan'

In [ ]:
Person._name

'kishan'

In [ ]:
Person._age

21

In [ ]:
Person.get_age()

21

In [ ]:
class Vehicle:
    def __init__(self, brand, model):
        self.brand = brand
        self.model = model

    def display_info(self):
        return f"{self.brand} {self.model}"

class Car(Vehicle):
    def __init__(self, brand, model, num_doors):
        super().__init__(brand, model)
        self.doors = num_doors

    def display_info(self):
        return f"{self.brand} {self.model} {self.doors}"

In [ ]:
my_car= Car('Maruthi Suzuki','Dzire',7)

In [ ]:
my_car.display_info()

'Maruthi Suzuki Dzire 7'

In [ ]:
class Animal:
  def make_sound(self):
    print("Animal makes a sound!")

class Dog(Animal):
  def make_sound(self):
    print("bark !!")

In [ ]:
dog1 = Dog()

In [ ]:
dog1.make_sound()

bark !!


In [ ]:
class Tiger(Animal):
  def make_sound(self):
    print("Hunts !!")

In [ ]:
Tg1= Tiger()

In [ ]:
Tg1.make_sound()

Hunts !!


In [ ]:
ani = Animal()

In [ ]:
ani.make_sound()

Animal makes a sound!


In [ ]:
class Example:
  def sum(self, *args):
    return sum(args)

In [ ]:
e = Example()

In [ ]:
e.sum(5, 2)

7

In [ ]:
e.sum(18, 17, 45, 7, 1, 254)

342

In [ ]:
import pandas as pd

In [ ]:
x = pd.Series([1, 2, 3, 4, 5])

In [ ]:
x

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
y = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

In [ ]:
y

A  B
0  1  4
1  2  5
2  3  6

In [ ]:
import numpy as np
td_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(td_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
import pandas as pd

renewable_sources = ['Hydro', 'Wind', 'Solar', 'Geothermal', 'Tidal']

rs = pd.Series(renewable_sources)

rs

0         Hydro
1          Wind
2         Solar
3    Geothermal
4         Tidal
dtype: object

In [ ]:
data = {
    'Project':['Hydro Plant','Wind Turbine','Solar Farm','Geothermal Station','Tidal Plant'],
    'Technology': ['Hydro','Wind','Solar','Geothermal','Tidal'],
    'Capacity(MW)':[150,300,200,50,175],
    'Cost(Million $)':[200,400,350,100,250],
    'Location':['North America','Europe','Asia','Africa','South America'],
    'YOC':[2023,2022,2021,2023,2022]
}


In [ ]:
df = pd.DataFrame(data)
df

Project  Technology  Capacity(MW)  Cost(Million $)  \
0         Hydro Plant       Hydro           150              200   
1        Wind Turbine        Wind           300              400   
2          Solar Farm       Solar           200              350   
3  Geothermal Station  Geothermal            50              100   
4         Tidal Plant       Tidal           175              250   

        Location   YOC  
0  North America  2023  
1         Europe  2022  
2           Asia  2021  
3         Africa  2023  
4  South America  2022

In [ ]:
df.columns

Index(['Project', 'Technology', 'Capacity(MW)', 'Cost(Million $)', 'Location',
       'YOC'],
      dtype='object')

In [ ]:
df['Technology']

0         Hydro
1          Wind
2         Solar
3    Geothermal
4         Tidal
Name: Technology, dtype: object

In [ ]:
high_capacity = df[df['Capacity(MW)'] > 150]
print(f'High Capacity Projects are : \n {high_capacity}')

High Capacity Projects are : 
         Project Technology  Capacity(MW)  Cost(Million $)       Location   YOC
1  Wind Turbine       Wind           300              400         Europe  2022
2    Solar Farm      Solar           200              350           Asia  2021
4   Tidal Plant      Tidal           175              250  South America  2022


In [ ]:
high_cost = df[df['Cost(Million $)'] > 300]
print(f'High Capacity Projects are : \n {high_cost}')

High Capacity Projects are : 
         Project Technology  Capacity(MW)  Cost(Million $) Location   YOC
1  Wind Turbine       Wind           300              400   Europe  2022
2    Solar Farm      Solar           200              350     Asia  2021


In [ ]:
df['Cost per MW'] = df['Cost(Million $)'] / df['Capacity(MW)']
df

Project  Technology  Capacity(MW)  Cost(Million $)  \
0         Hydro Plant       Hydro           150              200   
1        Wind Turbine        Wind           300              400   
2          Solar Farm       Solar           200              350   
3  Geothermal Station  Geothermal            50              100   
4         Tidal Plant       Tidal           175              250   

        Location   YOC  Cost per MW  
0  North America  2023     1.333333  
1         Europe  2022     1.333333  
2           Asia  2021     1.750000  
3         Africa  2023     2.000000  
4  South America  2022     1.428571

In [ ]:
total_cost = df['Cost(Million $)'].sum()
total_capacity = df['Capacity(MW)'].sum()

print(f'Total Cost of Projects : {total_cost} million $')
print(f'Total Capacity of Projects : {total_capacity} MW')

Total Cost of Projects : 1300 million $
Total Capacity of Projects : 875 MW


In [ ]:
grouped_data = df.groupby('Technology')['Capacity(MW)'].sum()
grouped_data

Technology
Geothermal     50
Hydro         150
Solar         200
Tidal         175
Wind          300
Name: Capacity(MW), dtype: int64

In [ ]:
import numpy as np
a = np.array([1,2])
a

array([1, 2])

In [ ]:
a.ndim

1

In [ ]:
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [ ]:
b.ndim

2

In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
c.ndim

3

In [ ]:
z = np.random.rand(4,4)
z

array([[0.14690128, 0.20825699, 0.81893697, 0.12331143],
       [0.98468025, 0.8618848 , 0.291821  , 0.64727415],
       [0.44319978, 0.07053162, 0.52112029, 0.13939499],
       [0.01326905, 0.84726572, 0.13840555, 0.26065181]])